# Generated by Django 4.2.6 on 2023-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ip', models.CharField(max_length=255)),
                ('request_data', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
